# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run:
          command: |
            git config user.name "circle-ci"
            git checkout gh-pages
            git merge --no-ff origin/master -m "AUTO BUILD ${CIRCLE_BUILD_URL}"
            make
            git add ./docs
            git commit -m "AUTO BUILD ${CIRCLE_BUILD_URL}"
            git remote add upstream https://${GITHUB_ACCESS_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
            git push upstream gh-pages:gh-pages

workflows:
    version: 2
    build-and-push:
        jobs:
            - build:
                filters:
                    branches:
                        only: master
